name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'  # Wähle deine Node-Version

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: npm run deploy  # Dieser Befehl sollte `firebase deploy` ausführen
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
